### ISSUE TITLE
LairdCP/wb.git is missing msd50n-laird-7.0.0.19.tar.bz2

### ISSUE THREAD

**Issue by Stretchdude** [LairdCP/wb-manifests#1]
Hi,

I try to build an ig60 buildroot image. Lots of download links in the repo scripts are broken. Here is the first I can't solve by downloading manually because I can't find this archive.

Full Link:
https://github.com/LairdCP/wb-manifests/releases/download/LRD-REL-7.0.0.19/msd50n-laird-7.0.0.19.tar.bz2
Alternativ tries point to sources.buildroot.net but there is nothing with this or a similar file name 

Thanks
Ben

**Comment by dankephart** [comment]
If building an IG60, please follow the correct instructions:
https://github.com/LairdCP/IG60-Laird-Linux-Release-Packages
